### ISSUE TITLE
Union on DataSinks does not work

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#112]
When you have a DataSink with several inputs you get this error message:
13/09/24 13:48:09 ERROR client.JobClient: ERROR: eu.stratosphere.nephele.executiongraph.GraphConversionException: Job and execution vertex <Unnamed File Data Sink> have different number of inputs
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createInitialGroupEdges(ExecutionGraph.java:409)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:282)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)

Fabian mentioned that having the compiler add a dummy mapper before the sink could be the solution.

**Comment by fhueske** [comment]
Yes, that should be a quick fix. But AFAIK this would result in one additional thread and serialization overhead, since [DataSinkTask](https://github.com/stratosphere/stratosphere/blob/master/pact/pact-runtime/src/main/java/eu/stratosphere/pact/runtime/task/DataSinkTask.java)s cannot be chained behind [RegularPactTask](https://github.com/stratosphere/stratosphere/blob/master/pact/pact-runtime/src/main/java/eu/stratosphere/pact/runtime/task/RegularPactTask.java)s, due to the different abstract Nephele interfaces for processing and output tasks.

Another solution could be to integrate the union logic directly into the [DataSinkTask](https://github.com/stratosphere/stratosphere/blob/master/pact/pact-runtime/src/main/java/eu/stratosphere/pact/runtime/task/DataSinkTask.java) as I did with the Sorter for Sorted output (see #164). However, this is actually duplicating complex code that is also taken care of by the [RegularPactTask](https://github.com/stratosphere/stratosphere/blob/master/pact/pact-runtime/src/main/java/eu/stratosphere/pact/runtime/task/RegularPactTask.java).

**Comment by StephanEwen** [comment]
That Nephele Class hierarchy has has always bothered us with respect to duplicate logic in souce and sink tasks. The Regular Pact Task has many static methods to set up outputs for example, such that the logic can be called from an input task. We can do similar things for the union (as a quick fix).

We should think about changing that class hierarchy, such that all tasks inherit from the same task class and implicitly become input and outputs. Potentially with a property to be set or a marker interface.

That would also help us to get around fake tails in the iterations.

**Comment by uce** [comment]
Yes, I agree with redoing the task hierarchy. I just quoted you and opened a separate issue #165.

**Comment by rmetzger** [comment]
The suggested quick fix works. We need to fix this soon!

**Comment by fhueske** [comment]
Done in pull request #307
