### ISSUE TITLE
Configuration setup

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#113]
I find it confusing to have configuration parameters set in different places. Besides the XML files in `conf` we also have configuration parameters in `bin/nephele-config.sh`. We could unify this by providing a script `conf/nephele-env.sh` which sets the respective environment variables and is included by `bin/nephele-config.sh`.

Any ideas or comments on this?

I would also appreciate a general discussion about our configuration setup. My main question is if we want to keep it in XML? What could be alternatives?

**Comment by fhueske** [comment]
+1 for configuration in a single place.

I think the XML config is fine. It is easy to understand by humans and can be parsed or generated by machines (given an XML parser).

**Comment by asteriosk** [comment]
Yes, it should be kept in a single place - it's always preferable.

The XML file is ok though: the current configuration is pretty flat
(property that has key and value) isn;t this an overkill? Simple key=value
should also work. Unless the XML is there for a specific reason, I prefer
simple, .ini-style configuration files - easier to edit and add new values.
Plus, you don't need an XML parser to do this simple thing (less
dependencies in the project): you read the conf file by line and you split
on the first '='. Then you trim the two resulting strings to remove
possible space. Done.

What is more, .ini style config files are easy to parse from shell scripts.

So, if someone finds it easy to replace the whole XML story by simple files
(named .conf or smth), I would be happy to get rid of XML. If this is an
overkill, let's keep what's already working.

**Comment by rmetzger** [comment]
+1 single file

I'd like to add support for other file formats, such as YAML or JSON. I think it should be easily possible to support multiple formats.

One has to add 4 lines for a single stupid key-value pair

``` xml
<property>
                <key>jobmanager.rpc.address</key>
                <value>localhost</value> 
</property>
```

compared to (YAML)

``` yaml
jobmanager.rpc.address: localhost
```

Yaml also supports nesting ( See https://github.com/dropwizard/dropwizard/blob/master/dropwizard-example/example.yml ) and everything else one wants ;)

See also this discussion: http://stackoverflow.com/questions/1925305/best-config-file-format

We could unify all configuration into ONE file. Even heapsize and other jvm related configuration. Since the format for yaml is so simple, it is possible to parse it using regular bash tools!

**Comment by uce** [comment]
Although XML is indeed easy to parse and understand, I find it way to verbose and repetitive (for humans).

I would go with @rmetzger's YAML proposal. :+1:

**Comment by andrehacker** [comment]
+1 singe config directory.
It is currently very easy to forget the (very important) heap-settings in nephele-config.sh.
Hadoop solves it as described by ufuk (they have a file `conf/hadoop-env.sh`) and I think this is the best way to do it.

I agree that XML is very verbose.
I think JSON is a bad alternative because it does not support comments  (see http://stackoverflow.com/questions/244777/can-i-comment-a-json-file).
Yaml looks great however.

**Comment by asteriosk** [comment]
The problem with YAML is that it is not trivially parseable from a bash
script. And in any other language, it will add an extra almost unneeded
library.

Lots of times I have regretted not using the simplest and most universally
accepted way of doing something (in this case, a key=value syntax).

In order to respond to the question  on the best candidate, could someone
answer these questions?
- how many variables are there going to be added?
- do we need to ever read them from bash?
- will we ever need to read from bash?

**Comment by aalexandrov** [comment]
+1 for YAML. Not sure how we're gonna parse this from the shell scripts though.

**Comment by andrehacker** [comment]
Being able to parse the config files from bash has an advantage: We could even get rid of an additional nephele-config.sh file and all configuration would be in the same folder AND in the same format (including taskmanager and jobmanager heapspace and processid folder which is currently defined in a .sh file).

This might be an answer to @asteriosk question "will we ever need to read from bash?"

**Comment by rmetzger** [comment]
Okay,

I'm still more convinced by YAML, because its a known format and has a full
fledged parser.

> In order to respond to the question on the best candidate, could someone answer these questions? 
> - how many variables are there going to be added? 

There are currently around 15 values. But there are a few more (I'd say 50 in total) that are not contained in the default file.

> - do we need to ever read them from bash? 

Yes. For jvm options. (See Andre, who was faster ;) )

**Comment by asteriosk** [comment]
I agree that YAML is everywhere and in fashion. But I'm still not convinced
that we need it: we would need it only if we need nesting (or else, it is
"key: value" instead of "key=value"). Thus, (since we _need_ to read from
bash) if we need nesting and you can provide a simple, no-hack way of
reading _nested_ YAML files from bash, I'm 100% with you! If not, I would
keep it simple.

cheers,
Asterios

**Comment by rmetzger** [comment]
How about using the YAML format, without using a Java-YAML parser. (Just as you said a simple class that splits lines and ":")
We can than pretend that we are super cool. If there is ever the need to use more advanced YAML features, we can keep the existing configuration files and use a more advanced parser.

**Comment by asteriosk** [comment]
For me it does not make a difference. My only point was to make sure that _we
can parse from bash_. If this is done, I don't care what the separator is
or what the file extension is. But in the end of the day, what's the point
of having: (1) ":" instead of "=" as separator, and (2) .yaml instead of
.conf as file extension, when we do not implement nesting and we actually
implement a classic, good old key=value config file?

We can let the others vote for:
1. "faux" yaml with ":" and ".yaml" (no nesting) or
2. traditional "=" and ".conf"

Then, just implement the most voted solution. But make sure we parse easily
from bash ;)

cheers,
Asterios

**Comment by rmetzger** [comment]
Hi,

> For me it does not make a difference. [...]
> But in the end of the day, what's the point of having: (1) ":" instead of "=" as separator, and (2) .yaml instead of .conf as file extension, when we do not implement nesting and we actually implement a classic, good old key=value config file?

You are right, there are technically no differences between ':' and '=' (also for bash-based parsing).

But by being compatible to YAML, we are using a _standardized_ file format. Other applications can easily read and write it, there are syntax checkers out there and there is no need to write additional documentation on the file format.
If we will ever have the need to use more than just key-value pairs, we might want to switch to a full YAML parser. If we then use a proprietary file format, we either have to implement our own parser for our own format (which does not make our product any better and is not our core competency) or we can just switch the parser.
Our project has currently almost no users, so we don't have to go through a painful migration. But by using a standard, we are able to use more advanced features, if we have to, even with a large user-base.

Thats why I think that it matters, at the end of the day, to choose yaml.

@aalexandrov: This solution only uses `sed` to parse yaml to bash: http://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script
Another way would be `grep` ing for the line and then splitting by the seperator with `cut`. (and some optional trimming with sed). The bash parsing is only done once at start up, so it does not have to be super fast.

Robert

**Comment by ktzoumas** [comment]
I think that Robert's solution satisfies all cases. So let us go for this
unless someone speaks up today. The important thing is to have a single
configuration file in a format that is familiar and friendly to modern
developers.

**Comment by aljoscha** [comment]
I like ini files.

**Comment by sscdotopen** [comment]
http://bikeshed.com/

**Comment by asteriosk** [comment]
Let's just go on - this is getting too long compared to its importance. Non-nested YAML does the work and everybody is happy with it.
