### ISSUE TITLE
Problems with WorksetConnectedComponents

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#136]
(1) The comments in WorksetConnectedComponents obviously refer to K-Means

(2) The wiring of the iteration seems to be wrong, the next workset is produced by joinWithNeighbors not by updateComponentId

```
iteration.setNextWorkset(updateComponentId);
iteration.setSolutionSetDelta(updateComponentId);
```

**Comment by StephanEwen** [comment]
Comments are fixed in 83e209b037dcf1f2c53d3a006c765bf5d77df133

The wiring is correct. There are multiple ways to express the job. You can rotate the operators around The loop formed by the workset feedback, since the workset feedback is logically just another edge. In your variant, the join with the edges is the last operation before the feedback, in the example variant, it is the first after.
