### ISSUE TITLE
Enhancement: Expand test coverage

### ISSUE THREAD

**Issue by physikerwelt** [stratosphere/stratosphere#208]
I propose to configure travis in a way that changes in stratosphere/stratosphere trigger re-running the tests in in other project that depend on stratosphere i.e. stratosphere-sopremo and other essential projects.
By that we could expand the "test coverage" without much effort and would have a chance to discover errors that are hard to detect manually, especially if there are dependencies to the -SNAPSHOT version.

**Comment by StephanEwen** [comment]
Can you change that independently in your build server setup? 

I think the crux of the issue is actually that meteor and other projects depend on a snapshot version. These version are bound to change on ways that cause problems for dependent projects.

My feeling is that a correct software engineering solution would be to push a version, say 0.3.0 or so, that represents the current snapshot and will not change. You could use that as a stable dependency. At some point you could move forward to 0.4, which is then stable, while we work on the snapshot version of 0.4.1

What do you think?

**Comment by physikerwelt** [comment]
Yes. I completely agree with you about the version numbers... and I think I'm not the only one.
However, I think a retrigger all tests would be nice for fixes and pre release checks.
I think we have to expect hotfixes for released versions and should think about a process how to deal with them. (Maybe in terms of version numbers?)

**Comment by physikerwelt** [comment]
I found that with a random work approach http://mojo.codehaus.org/buildnumber-maven-plugin/usage.html
I'm not yet quite sure if it's helpful or distracting but it would at least allow to set unique references.

**Comment by rmetzger** [comment]
Hey,

so I think in general, its a good idea to somehow store the version (e.g. the git revision id) in the snapshots, so that we can see which version a user has.
The best solution in my opinion is to write the id into the README.txt file.
I'm really against changing the name of the build again. (We would have to update all the documentation and examples etc.)
I don't see that the buildnumber-maven-plugin does support this (it can only write into .property file).

I think this plugin does everything we need (we need to try if it also can write into non .property files, but it looks like (since the're also writing into xml): https://github.com/ktoso/maven-git-commit-id-plugin

**Comment by fhueske** [comment]
I agree with @rmetzger. 
Having a VERSION file with an ID that can be linked to the last commit of the build is a very good idea and will help to identify bugs in user settings.
A new version number for each commit sounds a bit heavy weight to me.

**Comment by physikerwelt** [comment]
OK. We are moving a little bit into the "How to do releases?" Question.

In a former thread Robert explained, that the master branch moves from a stable state to the next stable state in terms of pull requests.
Stable state was defined as "all stratosphere tests are passed".
I propose to change the definition of stable state in the following:
"All stratosphere tests and all tests of important dependent projects are passed."

I think stratosphere-sopremo is an important dependent project. Furthermore I see the word-count sample and maybe some more basic examples as important dependent projects as well.
If you think the set of important dependent projects is empty. The definitions are equivalent and the issue should be closed.
If you think the set is not empty, we should discuss how, when and by whom the issue is going to be fixed.

I think the details of version numbering are a different issue... I feel sorry that I contributed to let the issue become "offtopic".

**Comment by fhueske** [comment]
I agree that sopremo is an important dependent project, but I think the definition of stable state should only depend on the project itself, as @StephanEwen suggested.
Dependent projects that request a stable version should refer to a stable version and not a development version.

Otherwise, updates such as changing the programming interface, which might still happen since we are not in a version 1.0 mode, would require to update all dependent projects. I do not think this is reasonable.
Updates that introduce bugs should be identified by the project's own test infrastructure. Relying on the tests of a dependent project does not seem to be the right way, IMHO. Sure, there will be cases where bugs are not detected, but these should be handled by adding test cases to the project itself and finally fixing the bug. 

Btw., the Stratosphere example jobs are part of the project itself and checked by integration tests.

**Comment by physikerwelt** [comment]
@fhueske I think that's a little bit problematic. The example jobs and scala are tested and sopremo is not tested.
To which stable version dependent projects should refer?  To 0.2? or 0.4 that is not yet released, and which probably won't be stable if it is released soon?

**Comment by StephanEwen** [comment]
We decided to solve this problem with periodic publications of minor releases that higher level layer projects like Metor/Sopremo can reference.
