### ISSUE TITLE
Change name of ScalaPlan to just Plan?

### ISSUE THREAD

**Issue by asteriosk** [stratosphere/stratosphere#222]
Should we rename the ScalaPlan to one of the following?

StratosphereJob or
Job or 
Plan

ScalaPlan feels a bit awkward. 

What do you think? @ktzoumas also agreed with this.

**Comment by sscdotopen** [comment]
+1 for Plan, simple and concise
Am 29.10.2013 09:36 schrieb "Asterios Katsifodimos" <
notifications@github.com>:

**Comment by StephanEwen** [comment]
I think this is a good question and applies to more than just the ScalaPlan. The current Java-based programs are also called Plan, which is an unfitting name, imho.

We could collect all these names and make one coordinated rename before the release.

Here are some suggestions to start with:
1.  **ScalaPlan** and **Plan** to whatever (I personally do not like Plan)
2.  Along the same lines, **PlanAssembler** sounds not too nice.
3.  The **Contract** classes are called to because of the initial theory behind that. I think it is a bit outdated and I have gotten the question a few times why we call these thinks contracts. Seems un-intuitive. Since we want to extend that anyways with other operators (filters, joins, aggs, ...), why not call everything operator or operation? MapOp or MapOperator?

Any comments and additions?

**Comment by StephanEwen** [comment]
I just saw @sscdotopen  is in favor of _Plan_. Everybody has a different intuition there ;-)

**Comment by fhueske** [comment]
How about "Program"? 
"Job" could refer to the execution of a program.

I agree with @StephanEwen in doing a consistent renaming of the user interface including Contracts and PlanAssember.

**Comment by ktzoumas** [comment]
Is creating an object even necessary?

**Comment by uce** [comment]
:+1: for keeping it simple.

I actually like Job more than Program (but I think @StephanEwen and @fhueske already had a consensus somewhere to prefer programs over jobs). One way or the other... can't we just stick with one of the two? Probably nobody will care and everybody will mix it anyways.

In spirit of simplicity: Can't we also rename Match to Join? I think we almost always find ourselves explaining Match as Join. And we don't need to break stuff here... we could just wrap Match to the renamed Join stuff and add `@deprecated` or something.

**Comment by sscdotopen** [comment]
+1 for Program and Join
Am 29.10.2013 16:57 schrieb "Ufuk Celebi" notifications@github.com:

**Comment by StephanEwen** [comment]
+1 for Join: What is now the Match is simply a join with a UDF.
+1 for Program or Job

@ktzoumas Creating an object is not necessary in many cases, when we use the shell or execute embedded. I think we should still have packaged programs that you can start from the command line. The program just describes what results the user wants, plus some global parameters (like desired degree of parallelism).

**Comment by StephanEwen** [comment]
For these objects, we can have the same for Java and Scala.

**Comment by ktzoumas** [comment]
@StephanEwen, I understand that, but I was wondering whether this can be
done without asking the user to type it in.

Otherwise, I vote for Job

**Comment by StephanEwen** [comment]
Subsumed by #257
