### ISSUE TITLE
Add JProfiler logo to website for free licences

### ISSUE THREAD

**Issue by akunft** [stratosphere/stratosphere#316]
We can get free open source licences for JProfiler if we put a text link / logo on our website. The question is where to put it. They prefer the frontpage or download page. I would prefer to put it in the footer cause it will destroy the look & feel of the site if we put it random in the download page in my opinion.

So, are there other opinions where to put the link / dislikes of the idea in general?

**Comment by rmetzger** [comment]
Hi,

Thanks for taking care of this!
I would also like to have JProfiler licenses because it seems to be the best profiling tool available.
I'm against putting the link in the footer because it is too prominent. The only reason why they want a link on our page is to improve their page rank. This goal can also be achieved by putting the link on our download page.

The last line on the DL page is "Feel free to contact us if you have any problems or suggestions.".
We could add a sentence like. "This project uses JProfiler to achieve its outstanding performance. Thanks for the open source license from ej-technologies."

**Comment by StephanEwen** [comment]
Do we know that the conditions are from the JProfiler side? If it is okay to place it under downloads, than I would vote for that option.

**Comment by rmetzger** [comment]
Their website states:

> We prefer the front page or the download page. 

http://www.ej-technologies.com/buy/jprofiler/openSource

**Comment by uce** [comment]
OK, perfect. Let's do it as @rmetzger proposed on the Download page then.

**Comment by akunft** [comment]
Alright. I'll do it tomorrow.
