### ISSUE TITLE
Create 0.5 documentation on website

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#410]
We need to start documenting new features such as the JDBC Output format, the CollectionDataSource.

The 0.5 documentation should not be linked by default.

**Comment by uce** [comment]
:+1: I think this is especially important in order to _not_ end up with a stop-the-world-documentation-week right before the release.

I would propose to just list the 0.5-snapshort-specific new features and not do a copy-0.4-and-add-stuff thing, because this will be hard to keep in sync with our static documentation setup.

**Comment by rmetzger** [comment]
I agree, maintaining two documentations at the same time will be horrible.
Okay, how about adding **one** page in the Documentation dropdown which says "0.5-SNAPSHOT".

The page contains "snippets" of documentation for features in development (such as JDBCOutputFormator CollectionDataSource).
Once 0.5 release is ready, we'll copy these snippets into the 0.4 docu and make it the new 0.5 documentation.
Agree?

**Comment by uce** [comment]
Yes, this is exactly what I meant. :+1: :laughing:

**Comment by uce** [comment]
You can [check it out](http://stratosphere.eu/docs/0.5/) online. It's only accessible via the drop down and the default documentation link still goes to the 0.4 docs. I think this is OK for now. We should add the content asap though.

**Comment by rmetzger** [comment]
Perfect! Thank you.
We'll instruct the authors of new features to write documentation.
