### ISSUE TITLE
Failing Testcases in 0.4 release

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#416]
Hello,
a Stratosphere user send me an email regarding two failing test cases in the current 0.4 stable release.

https://gist.github.com/rmetzger/8521843
https://gist.github.com/rmetzger/8521862

It seems to be an issue with the Scala interface?

Some more information
- openSuse 11.4
  Tested on three different computers 
  - Computer 1, User 1: works.
  - Computer 1, User 2: fails.
  - Computer 2, User 2: fails.
    Seems to be an issue with the user-environment or so?

Its the release-0.4 branch and the error occurs with mvn clean verify.

**Comment by StephanEwen** [comment]
Hmmm... And this did not cause the build to fail? Did we configure maven
incorrectly?

**Comment by rmetzger** [comment]
It seems that there is an error with the input parsing or so. It looks like part of the exception is missing.

**Comment by StephanEwen** [comment]
Okay. Is anyone onto the bug already?

**Comment by rmetzger** [comment]
I'm not sure if it is a local issue of the user. I asked for the full stack trace. (The user is from HU-Berlin)

**Comment by aljoscha** [comment]
Sorry, was a bit busy today...
Did anyone notice that in the first gist the problem is with the decimal point:

```
expected:<5|0|147828[.]97> but was:<5|0|147828[,]97>
```

Seems to be that his system is on german locale...

**Comment by StephanEwen** [comment]
Ah, ja, the java parsers are sensitive to that, good catch!

Can we make the locale configurable and always use en-us unless something
else is specified?

**Comment by rmetzger** [comment]
Okay, the user confirmed the bug by changing the locale for user 2 from german to english.

We have to make sure that we control the locale in the settings.
Which parser exactly is parsing the strings there?

**Comment by StephanEwen** [comment]
It is the DecimalTextDoubleParser in the stratosphere-core project. Same
issue will also hold for the DecimalTextFloatParser.

**Comment by aljoscha** [comment]
It is not because of the parsers. The problem is simply, that the scala job writes the output records using:

``` scala
"%d|%d|%.2f".format(item.orderId, item.shipPriority, item.revenue)
```

Where the format is the Java String.format() method that uses the default Locale on the system. In TPCHQuery3 we have harcoded values that have a dot, not a comma, as the "decimal point".

The java TPCHQuery3 uses CsvOutputFormat which simply does Float.toString() which, I'm guessing here, always uses a dot as a "decimal point".

The scala behaviour seems to be correct, but it's harder to test this....

What do you think? I could change the scala jobs to also use the CsvOutputFormat.

**Comment by aljoscha** [comment]
If more cases surface I will force a locale change there as well.
