### ISSUE TITLE
stratosphere scripts fail if the path contains spaces

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#466]
Hi,

a user reported this issue via email:

```
ruenau4 akunkel 5 ( Full install ) $ ./stratosphere/bin/start-local.sh
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
sed: can't read /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/conf/stratosphere-conf.yaml: No such file or directory
./stratosphere/bin/start-local.sh: line 23: /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/bin/jobmanager.sh: No such file or directory
gruenau4 akunkel 6 ( Full install ) $ pwd
/vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full install
```

**Comment by iasip** [comment]
Just leaving a note for other members that I'm hoping to get this issue resolved.

**Comment by iasip** [comment]
I wanted to discuss my first steps at resolving this issue.
1. I replicated the bug by running start-local.sh under the path "Desktop/Test Directory/".
2. Shell scripts that have problems with whitespace are usually missing double quotes somewhere, so I looked for arguments and variables that might need double quotes around them.
3. I found a few places in config.sh that might have needed double quotes:

a. The first is the readFromConfig function at Line 44:
(local value=`sed -n "s/^[ ]_${key}[ ]_: ([^#]_)._$/\1/p" ${configFile})
Because ${configFile} is not enclosed in double quotes, if you run sed on an example path like "Desktop/Test Directory/stratosphere/conf/stratosphere-conf.yaml", sed utility will take it as two arguments ("Desktop/Test" and "Directory/stratosphere/conf/stratosphere-conf.yaml") and only run on the first ("Desktop/Test").

b. The second is at Line 113: 
(STRATOSPHERE_ROOT_DIR_MANGLED=`manglePath $STRATOSPHERE_ROOT_DIR`). 
The manglePath function will take $STRATOSPHERE_ROOT_DIR as two arguments if it has a space in it. To avoid that, we would need double quotes around $STRATOSPHERE_ROOT_DIR.

c. The third is includes all the instances that readFromConfig is called:
(Lines 124, 156, 161, 165, 169, 173, 177)
If any of the three arguments (specifically the ${YAML_CONF}) had a space in it, without being enclosed in double quotes, one argument would be mistaken for multiple arguments.
1. To sum it up, enclosing variables/arguments in double quotes prevent functions from mistaking a single argument with whitespace as multiple arguments.  Adding the double quotes that I mentioned above got rid of the "sed: can't find ..." error messages.
2. Unfortunately, I'm now getting the error message: 
   ./stratosphere/bin/start-local.sh: line 23: /Desktop/Test: No such file or directory 
   which is different from the original error message above:
   ./stratosphere/bin/start-local.sh: line 23: /vol/fob-vol2/mi08/akunkel/StratosphereWBI/Full/bin/jobmanager.sh: No such file or directory

Any help and criticism are welcome.

**Comment by rmetzger** [comment]
Hi,
thanks for taking care of the issue!

Your approach seems reasonable.
I think fixing the second problem "./stratosphere/bin/start-local.sh: line 23: /Desktop/Test: No such file or directory " should be easy.
Something like

``` bash
/bin/sh "$STRATOSPHERE_BIN_DIR/jobmanager.sh" start local
```

should do it.

**Comment by iasip** [comment]
Robert, your suggestion worked perfectly.  After correcting everything, I get the message "Starting job manager".
Could you direct me to where the shell scripts are located in the repo so that I may submit a pull request?
Thanks a lot.

**Comment by rmetzger** [comment]
Hi,
cool!

``` bash
find . | grep "jobmanager.sh"
```

Will point you to

```
./stratosphere-dist/src/main/stratosphere-bin/bin/jobmanager.sh
```

This is where the scripts are located.

**Comment by rmetzger** [comment]
Fixed in https://github.com/stratosphere/stratosphere/pull/521.
