### ISSUE TITLE
Move gh-pages branch to seperate repository

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#487]
The gh-pages branch blows up our repo and initial checkout takes quite long. Also both things are seperate.

We might want to move gh-pages to a seperate repo.

Note: if we do this, we have to fix the "Edit this page" link of the documentation.

**Comment by rmetzger** [comment]
Hi,
we should certainly do this! I will create a repository in the stratosphere organization.
I would like to do the migration on the next Sunday, thats the day where we have the least traffic.
I'm not sure how the migration will work. We can not just push the gh-pages into the master of the web-repo. GitHub will complain because the domain is already registered with another repository. 
Can you ask GitHub how to do the migration?

**Comment by rmetzger** [comment]
Okay, I'm doing it now.

I pushed the branch to the new repository. Now I'll check if it is working from the new one.

**Comment by rmetzger** [comment]
Okay, the move was successful. I'll delete the `gh-pages` branch here.
