### ISSUE TITLE
Descending group sorting does not work.

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#588]
The flag that describes whether comparisons should result in an ascending or descending order is not used by any of the basic type comparators.

**Comment by twalthr** [comment]
You mean something like that in every Comparator, right?

<code>
@Override
    public int compare(DataInputView firstSource, DataInputView secondSource) throws IOException {
        double l1 = firstSource.readDouble();
        double l2 = secondSource.readDouble();
        int comp = (l1 < l2 ? -1 : (l1 > l2 ? 1 : 0));
        return ascendingComparison ? comp : -comp;
    }
</code>

**Comment by StephanEwen** [comment]
Exactly

**Comment by markus-h** [comment]
Is this fixed? I am working on testcases for groupReduce and the descending order seems to be not working. I think this is connected to this issue.

**Comment by fhueske** [comment]
No, I don't think this is fixed. I have the same issue with a deactivated test in `ReduceITCase`.

**Comment by twalthr** [comment]
I will do it, tomorrow. ok?

**Comment by markus-h** [comment]
:+1:

**Comment by fhueske** [comment]
I had to remove the GroupSorting test in the `ReduceITCase` because we do no longer support group sorting for the pair-wise `ReduceFunction`.
However, we should check if this solves the problem with GroupSorting (Ascending and Descending) in the `GroupReduceITCase`.

**Comment by markus-h** [comment]
@twalthr and me are working on it. The simple change mentioned above seems not to work.

**Comment by fhueske** [comment]
Great! Thanks! :smile:

**Comment by markus-h** [comment]
Ok, here are my investigations:
What I do is a `groupBy(1).sortGroup(0,Order.DESCENDING)`. In the compiler post pass the localStrategyComparator of the channel to the reduce is correctly set to [0] LongComparator(asc) and [1] IntComparator(desc). Both comparators are instantiated, but the second one is never used. I set a breakpoint inside the compare() method and it is never called.

So I had a look at the ReduceDriver, more specifically to the KeyGroupedIterator and its ValueIterator and I don't see how there should be support for sorted values inside of a group.

Is there runtime support for sorted groups in the reduce?

**Comment by fhueske** [comment]
The `BaseTypeComparator`s are bundled in a `TupleComparator` which uses them internally. Depending on the types that the `TupleComparator` needs to check, it might use normalized keys. Whether normalized keys can be used (for a prefix of the sorting key) is checked in the constructor of the `TupleComparator`. For this part, the comparisons are done on binary data and `compare()` will not be called. Since normalized keys do not work for descending sort (AFAIK), `compare()` should be called for attribute `0` if the comparison of attribute `1` returns 0 (equality).

I suspect that there is something not working correctly in the `TupleComparator`.

**Comment by fhueske** [comment]
I merged #693 which fixes the `compare()` methods of the base type comparators. The comparators need to be checked by tests (#589).

However, #693 does not (fully) solve this issue.

**Comment by filiphaase** [comment]
Hey I investigated this problem a little bit today. And as I see it the Ascending sort is also not working properly. If I change this:

``` java
//data.add(new Tuple3<Integer, Long, String>(16,6l,"Comment#10"));
data.add(new Tuple3<Integer, Long, String>(22,6l,"Comment#10"));
```

in the CollectionDataSets, testcase 3 of  GroupReduceITCase(which is testing sort-ascending) also breaks, while the result should be independent from the first value of the tuple.

I also found the source of the bug: I think the Comparators are reading data from wrong positions in the memory. I looked into the LongComparator compare() methods and the long values which they read have wrong values. But if I add this code both cases work:

``` java
    @Override
    public int compare(DataInputView firstSource, DataInputView secondSource) throws IOException {
        firstSource.skipBytes(4);
        secondSource.skipBytes(4);
        long l1 = firstSource.readLong();
        long l2 = secondSource.readLong();
        int comp = (l1 < l2 ? -1 : (l1 == l2 ? 0 : 1)); 
        return ascendingComparison ? comp : -comp;
    }
```

So I assume the offsets are not set properly, because the 4 bytes I skipped here are the 4 bytes of the first int value in the tuples.

But so far I don't know how to fix this.  I thought one could adjust that in the TupleComparator.compare() method, but I did not find a way to get memory-offsets for the different value positions.

**Comment by fhueske** [comment]
@zentol @StephanEwen I believe this issue has been fix, right?

**Comment by zentol** [comment]
i think so. The deactivated test in GroupReduceITCase (13 i think...) succeeded when i tried it. I also created two simple tests that check whether ascending/descending flag is passed from a plan to the comparators, both work.

**Comment by fhueske** [comment]
Great! @StephanEwen activated the last two tests in `GroupReduceITCase`.
I'm closing this issues.
