### ISSUE TITLE
Add Tests for the basic type utils

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#589]
We need thorough test for the basic type utils, as they are a core part of the API type system.

**Comment by fhueske** [comment]
This issue refers to the untested serializers and comparators in the `stratosphere-core` module in package `eu.stratosphere.api.common.typeutils.base` for the basic data types:
- Boolean
- Byte
- Char
- Double
- Float
- Int
- Long
- Short
- String

The *ValueSerializer classes are for the data types of our old Java API which will be depreciated in the future. 

We need thorough unit-tests for all of these classes because they will be heavily used. The tests should be put in the test directory of the `stratosphere-core` module in the same package as the tested classes. 

I would start with tests for the *Serializer classes. and continue with the *Comparator classes.

**Comment by StephanEwen** [comment]
I think we should retain the value types of mutable versions of javas
primitives.

**Comment by StephanEwen** [comment]
Have a look at the string array serializer tests. It uses a serializer test
util that makes it easy to add serializer tests.

**Comment by StephanEwen** [comment]
stratosphere-java/src/main/java/eu/stratosphere/api/java/typeutils/runtime/StringArraySerializer.java
and the associated test.

**Comment by aaronchlam** [comment]
I will be working on *Serializer tests in this issue and then move on to do the *Comparator if someone else does not get to it first.

**Comment by fhueske** [comment]
With  #745, the serializers for all nine primitive types are covered with unit tests.
Thanks @aaronchlam !

Tests for comparators are addressed by issue #744
