### ISSUE TITLE
Cost estimation problem for branched plans

### ISSUE THREAD

**Issue by tillrohrmann** [stratosphere/stratosphere#613]
I encountered the problem of negative cumulative costs for a plan which contained branched nodes. The problem is that the costs for branched nodes are not correctly calculated if one branched node x is contained in a cycle of another branched node y. Assuming that y is closed first, then closing of x will calculate too high double counted costs. To illustrate this case consider the following flow:

<pre>
     A ---- D
   /  \   /  \
SRC     \   SINK
   \  /   \  /
     B ---- C
</pre>

Assuming that the costs of all nodes except for SRC is 0 and the cost of SRC is 1, then SINK should have cumulative costs of 1 at the end. But executing the algorithm will calculate the following sequence.

SRC = 1
A = SRC = 1
B = SRC = 1
D = A + B - SRC (as a joined branching node) = 1
C = A + B - SRC = 1
SINK = D + C - A (as a joined branching node) - B (as a joined branching node) = 0

Thus the problem originates from a wrong accounting of branching nodes. A possible solution for this problem could be to split the predecessor costs according to the out degree of the predecessor node. By doing this, we wouldn't need to subtract double counted costs. But I'm not aware of any side effects this could have....

**Comment by StephanEwen** [comment]
I see the problem that you encounter. The branching logic tracks "already
closed branches" to not close them multiple times. But that does not work
properly for the cumulative costs.

I really like the idea of splitting the costs according and distributing
them over the outputs. The implication is that the cumulative costs at some
points are not the proper cumulative costs. Since the cumulative costs are
used for pruning, this might change things. But from the top of my head, I
cannot think of a pathological case.

So I would agree with the solution.
 Am 19.03.2014 18:53 schrieb "Till Rohrmann" notifications@github.com:

**Comment by tillrohrmann** [comment]
I tried to split the costs among the successors and all test cases pass so far. However, I suspect that there are not many test cases testing the optimiser and the cost estimation and thus I might miss something. If you want to, I can just make a pull request out of it.

**Comment by StephanEwen** [comment]
The solution sounds good to me. I'd be happy to take a pull request for this :-)

**Comment by fhueske** [comment]
Closed through #632
