### ISSUE TITLE
Setup issues with instance types

### ISSUE THREAD

**Issue by dimalabs** [stratosphere/stratosphere#78]
This task is for Tobias and Andreas (I don't know their github accounts)

**Comment by uce** [comment]
Some questions regarding this:
- Do we actually need to distinguish between different instance types at all?
- Wasn't this only relevant for the EC2 cloud manager which we removed?
- Doesn't  YARN make different instance types (which we need to manage) obsolete?

Can someone educate me on this issue? :bowtie:

**Comment by StephanEwen** [comment]
Since instances do not appear in the configuration any more, this issue is not visible to users any more.

The internal workings of the instance manager need to be rethought, but it should currently work if there is always just one simple single default instance against which all instances are matched.

**Comment by rmetzger** [comment]
This issue dates back to our first Stratosphere open source meeting. The "bug situation" has changed, so I'm moving this issue to a later release.
