### ISSUE TITLE
javadoc

### ISSUE THREAD

**Issue by jvf** [stratosphere/stratosphere#802]
Was created accidentally. It seems I can not delete anymore...

**Comment by fhueske** [comment]
no prob. ;-)

**Comment by rmetzger** [comment]
As a side note: If you were looking for some javadocs, I have setup a website contains the JavaDocs for the latest SNAPSHOT version: http://stratosphere-javadocs.github.io/
We have not made it fully public yet since we are still working on the docs. Note that the website only contains JavaDocs for the user-facing APIs

**Comment by jvf** [comment]
Awesome, thats what I was looking for!
