### ISSUE TITLE
Extending a FlatMapFunction with generics leads to a TypeExtractor error

### ISSUE THREAD

**Issue by atsikiridis** [stratosphere/stratosphere#842]
When trying to use a `DummyFlatMapFunction` that extends `FlatMapFunction` with generics I get a type extractor error.

To replicate this consider a mapper with the following signature:

```
public class DummyFlatMapFunction<A,B,C,D> extends FlatMapFunction<Tuple2<A,B>, Tuple2<C,D>> implements Serializable
```

and then try using in the following way:

```
DataSet<Tuple2<Text, LongWritable>> words = text.flatMap(new DummyFlatMapFunction<LongWritable, Text, Text, LongWritable>());
```

This outputs the following stack of exceptions when executed:

```
sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.reflect.TypeVariable
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.reflect.TypeVariable
    at eu.stratosphere.api.java.typeutils.TypeExtractor.createTypeInfoWithTypeHierarchy(TypeExtractor.java:415)
    at eu.stratosphere.api.java.typeutils.TypeExtractor.createTypeInfo(TypeExtractor.java:117)
    at eu.stratosphere.api.java.typeutils.TypeExtractor.getFlatMapReturnTypes(TypeExtractor.java:48)
    at eu.stratosphere.api.java.operators.FlatMapOperator.<init>(FlatMapOperator.java:34)
    at eu.stratosphere.api.java.DataSet.flatMap(DataSet.java:141)
```

The way I understand it is that the `TypeExtractor` does not support this with generics. In the examples of the new Java API all extended `FlatMapFunction` are with concrete types and not generics. However,  in `ConnectedComponents` the mapper that extends the MapFunction (not `FlatMapFunction`) is with generics and apparently works.

Is this behaviour expected and generics are not allowed with `FlatMapFunction` or am I missing something? Thanks.

**Comment by twalthr** [comment]
It seems you are getting an exception while the exception message is being created. This is a bug, I will fix it. However, the intended message should be "Type of TypeVariable XYZ could not be determined. This is most likely a type erasure problem."

This is a very common issue with the TypeExtractor, but we can not prevent this Exception. Due to type erasure, Java throws all generic parameters away, if you use:

``` java
new Function<ClassA,ClassB>();
```

The parameters stay only present if you extend from it:

``` java
new Function<ClassA,ClassB>() { };
```

If you would use a 
`class PythonIdentityMapper<IN> extends MapFunction<IN,IN>`
then the TypeExtractor recognizes the same variable (name) and use the Input type as output type.

**Comment by atsikiridis** [comment]
Hello, Thank you very much for the input.

**Comment by fhueske** [comment]
So I guess we need to wait for the ResultTypeQueryable interface (#845) to have a proper solution.
In the meantime, you could start to implement the interface for the HadoopFunction Wrappers.
It won't work for now, but once #845 is fixed, you can check if it is working.

**Comment by fhueske** [comment]
I close this issue as it is a consequence of #845
