### ISSUE TITLE
groupBy operator followed by a reduceGroup does not group Writables correctly

### ISSUE THREAD

**Issue by atsikiridis** [stratosphere/stratosphere#860]
I am not sure if it is a known issue, but If we consider the following `DataSet<Tuple2<Text,LongWritable>>` named `words` with the content:

allen 1
allein 1
allein 1
a 1
word 1
word 1
words 1

and apply `words.groupBy(0).reduceGroup(someReduceFunction)` (for example one that sums values)

outputs:

a 1
words 3
words 3

The same occurs when we specify a custom `KeySelector` that transforms the Text to a String (thw whole key as String).

**Comment by zentol** [comment]
is the code you used available somewhere?

**Comment by atsikiridis** [comment]
Hello @zentol , https://github.com/atsikiridis/stratosphere/blob/HadoopCompatibilityJAPIReady/stratosphere-addons/hadoop-compatibility/src/main/java/eu/stratosphere/hadoopcompatibility/mapred/example/FullWordCount.java

You can try running this one from my branch. Thanks!

**Comment by atsikiridis** [comment]
Or actually the testcase HadoopFullJobITCase on the same branch. Should be more convenient

**Comment by fhueske** [comment]
Hi,

I wrote my own program (below) and could **not** reproduce the error.
Will check your code and see what's different.

```
public static void main(String[] args) throws Exception {
        ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();

        List<Tuple2<String, Long>> data = new ArrayList<Tuple2<String, Long>>();
        data.add(new Tuple2<String, Long>(new String("allen"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("allein"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("allein"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("a"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("word"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("word"), new Long(1)));
        data.add(new Tuple2<String, Long>(new String("words"), new Long(1)));

        DataSet<Tuple2<String, Long>> myData = env.fromCollection(data);

        DataSet<Tuple2<Text, LongWritable>> res = myData
                .map(new MapFunction<Tuple2<String, Long>, Tuple2<Text, LongWritable>>() {

                    @Override
                    public Tuple2<Text, LongWritable> map(
                            Tuple2<String, Long> value) throws Exception {
                        return new Tuple2<Text, LongWritable>(new Text(value.f0), new LongWritable(value.f1));
                    }
                })
                .groupBy(0)
                .reduceGroup(
                    new GroupReduceFunction<Tuple2<Text,LongWritable>, Tuple2<Text,LongWritable>>() {

                        @Override
                        public void reduce(
                                Iterator<Tuple2<Text, LongWritable>> values, Collector<Tuple2<Text, LongWritable>> out) {

                            long sum = 0;
                            Tuple2<Text,LongWritable> v = null;
                            while(values.hasNext()) {
                                v = values.next();
                                sum += v.f1.get();
                            }
                            v.f1 = new LongWritable(sum);
                            out.collect(v);
                        }
                    }
                );
        res.print();
        env.execute();
    }
```

**Comment by atsikiridis** [comment]
Hello @fhueske thanks for testing. Maybe this is only when I use generics (in my example) plus I subclass `HadoopMapFunction`, `HadoopReduceFunction` ? I do that in order avoid type erasure issues and the `TypeExtractor` complaining (#845 and consequences) .

**Comment by zentol** [comment]
i doubt it has to do with generics. 
i placed system.outs in the `ReducerTransformingIterator.next()` and `HadoopOutputCollector.collect()` methods.

the following is an exempt: (ignore the different formatting)

```
iterator: hoechste 1
collector (hoechste, 1)
iterator: hohe 1
collector (hohe, 1)
iterator: hohen 1
iterator: (hohen, 1)
collector (holden, 2)
iterator: holden 1
collector (holden, 1)
```

it seems that sometimes the key is changed between the call to next and collect.

**Comment by atsikiridis** [comment]
Hi @zentol ,well there is definitely something wrong with the `ReducerTransformingIterator` and I think I have misundestood something  about groupBy. Was a bit in a rush to create this issue :-) Thanks for checking everybody.

**Comment by fhueske** [comment]
I know what the problem is, as usual the mutable objects returned by the reduce iterator. 
So this is a bug in the HadoopReduceFunction and nothing that blocks the release.

I'll share the details later this evening.

**Comment by uce** [comment]
+1 to Stephan's suggestion (outside this discussion... I'll edit this message if I find a reference) to return new objects per default and reuse objects as an "advanced" option.

@fhueske You mean later this night? ;-)

**Comment by fhueske** [comment]
Alright ;-) The problem is caused by the iterator that is given to the GroupReduceFunction. This iterator uses two mutable objects and continuously overrides their state on hasNext() calls. In this specific case there are two Tuple2 objects (A and B) which are returned one after the other by the iterator. If next() returns object A, the consecutive hasNext() call overwrites object B by the next element in the iterator. The following next() call returns B and hasNext() overwrites A, and so on. Also the fields of the tuples are reused. Therefore, there are also only two Text objects used during processing.

So what is happening here? At the start of a new group, the ReducerTransformingIterator reads the first tuple and extracts the key. The reference to this Text object is given to the Hadoop Reduce function and used there during the complete reduce() call. While processing the group, every second call of hasNext() on the iterator overwrites the state of the Key object. Since the key is always the same within a group this does not matter. However, the last call of hasNext() loads the first element of the next group in the current mutable object (which is hold back for the next group). Depending on the number of elements in the group (even or odd) the mutable object which is overwritten was the one from which the initial key was extracted and therefore the key object is also overwritten with the key value of the next group.

So a safe and straight-forward way to handle this is to copy the key value into a separate (mutable) object which is given to the Hadoop Reduce function.

**Comment by atsikiridis** [comment]
@fhueske , thanks a bunch for the detailed explanation. Aaa `hasNext()` is called by my own example in Hadoop and of course, mutable types. Confused me and started blaming the grouping. Thanks :) I'm definitely writing unit tests for this now...

**Comment by rmetzger** [comment]
I think we should have this explanation and a warning in the Javadocs here: http://stratosphere-javadocs.github.io/eu/stratosphere/api/java/functions/GroupReduceFunction.html
